package projecteuler
/**
Pentagon numbers
Problem 44
Published on Friday, 23rd May 2003, 06:00 pm; Solved by 22381
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk  Pj| is minimised; 
what is the value of D?
 */
object Problem44 {
  def main(args: Array[String]): Unit = {
    val pentagons = Stream.tabulate(Int.MaxValue){x => x * (3 * x - 1) /2}.tail
    val headsSet = pentagons.take(2500).toSet
//    def isPentagons(n: Int) = pentagons.dropWhile(_ < n).head == n
    def isPentagons(n: Int) = headsSet.contains(n)
    val pairs = pentagons.take(2000).toList.combinations(2).map {
      case x :: y :: Nil => (x, y)
      case _ => (0, 0)}.filter(x => isPentagons(x._1 + x._2) && isPentagons(x._2 - x._1))
    println(pairs.toList)
    println(pairs.map(x => x._2 - x._1).min)
  }
}