package projecteuler
/**
 * Triangular, pentagonal, and hexagonal
 * Problem 45
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
 * Pentagonal      Pn=n(3n1)/2     1, 5, 12, 22, 35, ...
 * Hexagonal       Hn=n(2n1)       1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */
object Problem45 {
  def main(args: Array[String]): Unit = {
    def isPentagon(n: Long) = {
      val x = 1 + 24 * n
      val t = Math.sqrt(x).toLong
      t * t == x && t % 6 == 5
    }
    def isHexagon(n: Long) = {
      val x = 1 + 8 * n
      val t = Math.sqrt(x).toLong
      t * t == x && t % 4 == 3
    }
    def triangles = Stream.tabulate(Int.MaxValue)(n => n * (n + 1L) /2).tail
    println(triangles.drop(285).find(x => isPentagon(x) && isHexagon(x)).get)
  }
}